### ISSUE TITLE
Adding an external package repository

### ISSUE THREAD

**Issue by tgvaughan** [4ment/flc#1]
Hi Mathieu, just in case you weren't aware: you can create your own external package file, host it somewhere (eg github pages) and tell potential users to add its url via the "manage external repositories" button in the beauti package manager. Your package (and any updates you make) will then be automatically available for download using the package manager, meaning that people can avoid having to do the installation by hand.

**Comment by 4ment** [comment]
Created a package.xml file on 4ment.github.io.
Added instructions to the README file about the installation process.
